{% set name = "pycrlibm" %}
{% set version = "1.0.4.dev0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/taschini/pycrlibm.git

build:
  number: 0
  script:
    - make crlibm
    - python setup.py install

requirements:
  host:
    - python {{PY_VER}}*|>=3.4
    - pip
  run:
    - python

test:
  imports:
    - crlibm

about:
  home: https://github.com/taschini/pycrlibm
  license_file: LICENSE
  summary: Python bindings for CRlibm
  doc_url: https://pycrlibm.readthedocs.io

extra:
  recipe-maintainers:
    - jrhawley
