{% set name = "pycrlibm" %}
{% set version = "1.0.4.dev0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/taschini/pycrlibm.git

build:
  number: 0
  script: "$PYTHON -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python>=3
    - pip
  run:
    - python

test:
  imports:
    - interval

about:
  home: https://github.com/taschini/pycrlibm
  license_file: LICENSE
  summary: Python bindings for CRlibm

extra:
  recipe-maintainers:
    - jrhawley
